#!/bin/bash
#
# Daily Digest API - One-line Installer
#
# USAGE:
#   Remote: curl -fsSL https://raw.githubusercontent.com/joshuakiefer/daily-digest/main/install.sh | bash
#   Local:  bash install.sh
#
# This script will:
# - Install system dependencies (Python, git, etc.)
# - Set up Python virtual environment
# - Clone/download the application
# - Interactively configure API keys
# - Set up systemd service (optional)
# - Start the application

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
APP_NAME="daily-digest"
APP_DIR="$HOME/$APP_NAME"
GITHUB_REPO="joshuakiefer/daily-digest"
GITHUB_BRANCH="main"

# Functions
print_header() {
    echo -e "${BLUE}"
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                                                            ║"
    echo "║           Daily Digest API - Installation Script          ║"
    echo "║                                                            ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

ask_question() {
    local question="$1"
    local default="$2"
    local response

    if [ -n "$default" ]; then
        read -p "$(echo -e ${BLUE}❓${NC}) $question [$default]: " response
        echo "${response:-$default}"
    else
        read -p "$(echo -e ${BLUE}❓${NC}) $question: " response
        echo "$response"
    fi
}

ask_yes_no() {
    local question="$1"
    local default="${2:-n}"
    local response

    if [ "$default" = "y" ]; then
        read -p "$(echo -e ${BLUE}❓${NC}) $question (Y/n): " response
        response="${response:-y}"
    else
        read -p "$(echo -e ${BLUE}❓${NC}) $question (y/N): " response
        response="${response:-n}"
    fi

    [[ "$response" =~ ^[Yy]$ ]]
}

check_os() {
    print_info "Checking operating system..."

    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if [ -f /etc/os-release ]; then
            . /etc/os-release
            OS=$NAME
            VER=$VERSION_ID
            print_success "Detected: $OS $VER"
        else
            print_error "Cannot detect Linux distribution"
            exit 1
        fi
    else
        print_error "This script only supports Linux (Ubuntu/Debian)"
        print_info "For other systems, please see manual installation in README.md"
        exit 1
    fi
}

install_dependencies() {
    print_info "Installing system dependencies..."

    # Update package list
    sudo apt-get update -qq

    # Install required packages
    sudo apt-get install -y \
        python3 \
        python3-pip \
        python3-venv \
        git \
        curl \
        ca-certificates \
        > /dev/null 2>&1

    print_success "System dependencies installed"
}

setup_application() {
    print_info "Setting up application..."

    # Check if directory exists
    if [ -d "$APP_DIR" ]; then
        if ask_yes_no "Directory $APP_DIR already exists. Overwrite?" "n"; then
            rm -rf "$APP_DIR"
        else
            print_error "Installation cancelled"
            exit 1
        fi
    fi

    # Clone or download
    if ask_yes_no "Clone from GitHub?" "y"; then
        print_info "Cloning repository..."
        git clone "https://github.com/$GITHUB_REPO.git" "$APP_DIR"
        cd "$APP_DIR"
    else
        print_info "Downloading latest release..."
        mkdir -p "$APP_DIR"
        cd "$APP_DIR"
        # Download files directly
        curl -sL "https://github.com/$GITHUB_REPO/archive/refs/heads/$GITHUB_BRANCH.tar.gz" | tar xz --strip-components=1
    fi

    print_success "Application files downloaded"
}

setup_python_environment() {
    print_info "Setting up Python virtual environment..."

    cd "$APP_DIR"

    # Create virtual environment
    python3 -m venv venv

    # Activate virtual environment
    source venv/bin/activate

    # Upgrade pip
    pip install --upgrade pip > /dev/null 2>&1

    # Install requirements
    print_info "Installing Python packages (this may take a minute)..."
    pip install -r requirements.txt > /dev/null 2>&1

    print_success "Python environment configured"
}

configure_api_keys() {
    print_header
    echo -e "${BLUE}API Configuration${NC}"
    echo ""
    echo "Let's configure your API keys. You can skip any and add them later."
    echo "Press Enter to skip an API key."
    echo ""

    cd "$APP_DIR"

    # Start building .env file
    cat > .env << 'EOF'
# Daily Digest API Configuration
# Generated by install.sh

EOF

    # Claude AI (most important)
    echo -e "${GREEN}Claude AI${NC} (Anthropic) - Required for AI summaries"
    echo "Get it from: https://console.anthropic.com/"
    ANTHROPIC_KEY=$(ask_question "Claude API Key (sk-ant-...)" "")
    if [ -n "$ANTHROPIC_KEY" ]; then
        echo "ANTHROPIC_API_KEY=$ANTHROPIC_KEY" >> .env
        print_success "Claude AI configured"
    else
        echo "ANTHROPIC_API_KEY=" >> .env
        print_warning "Claude AI skipped - AI summaries will not work"
    fi
    echo ""

    # Gmail
    echo -e "${GREEN}Gmail API${NC}"
    echo "Gmail requires OAuth tokens. You have two options:"
    echo "  1. Copy tokens from tokens.json (if you've already generated them)"
    echo "  2. Manually enter Client ID, Secret, and Refresh Token"
    echo ""

    # Check if tokens.json exists
    if [ -f "setup/google_credentials/tokens.json" ] || [ -f "token.json" ]; then
        print_success "Found Google tokens file!"
        if ask_yes_no "Use existing tokens.json file?" "y"; then
            print_success "Gmail will auto-load from tokens.json"
            print_info "No need to add to .env - config.py will load automatically"
            echo "# Gmail - will auto-load from setup/google_credentials/tokens.json" >> .env
            echo "GMAIL_CLIENT_ID=" >> .env
            echo "GMAIL_CLIENT_SECRET=" >> .env
            echo "GMAIL_REFRESH_TOKEN=" >> .env
        else
            echo "GMAIL_CLIENT_ID=$(ask_question 'Gmail Client ID' '')" >> .env
            echo "GMAIL_CLIENT_SECRET=$(ask_question 'Gmail Client Secret' '')" >> .env
            echo "GMAIL_REFRESH_TOKEN=$(ask_question 'Gmail Refresh Token' '')" >> .env
            print_success "Gmail configured manually"
        fi
    else
        print_warning "No tokens.json found"
        if ask_yes_no "Configure Gmail API manually?" "n"; then
            echo "GMAIL_CLIENT_ID=$(ask_question 'Gmail Client ID' '')" >> .env
            echo "GMAIL_CLIENT_SECRET=$(ask_question 'Gmail Client Secret' '')" >> .env
            echo "GMAIL_REFRESH_TOKEN=$(ask_question 'Gmail Refresh Token' '')" >> .env
            print_success "Gmail configured"
        else
            echo "GMAIL_CLIENT_ID=" >> .env
            echo "GMAIL_CLIENT_SECRET=" >> .env
            echo "GMAIL_REFRESH_TOKEN=" >> .env
            print_info "To generate tokens later:"
            print_info "  1. Place credentials.json in setup/google_credentials/"
            print_info "  2. Run: python setup/get_google_tokens.py"
        fi
    fi
    echo ""

    # NewsAPI
    if ask_yes_no "Configure NewsAPI?" "n"; then
        echo "https://newsapi.org/"
        echo "NEWS_API_KEY=$(ask_question 'NewsAPI Key' '')" >> .env
        print_success "NewsAPI configured"
    else
        echo "NEWS_API_KEY=" >> .env
    fi
    echo ""

    # Weather
    if ask_yes_no "Configure Weather API (OpenWeatherMap)?" "n"; then
        echo "https://openweathermap.org/api"
        echo "WEATHER_API_KEY=$(ask_question 'Weather API Key' '')" >> .env
        print_success "Weather API configured"
    else
        echo "WEATHER_API_KEY=" >> .env
    fi
    echo ""

    # Google Calendar
    echo "GOOGLE_CALENDAR_CREDENTIALS=" >> .env

    # Google Maps
    echo "GOOGLE_API_KEY=" >> .env
    echo "TRAFFIC_API_KEY=" >> .env

    # Todoist
    if ask_yes_no "Configure Todoist?" "n"; then
        echo "Get token from: https://todoist.com/app/settings/integrations"
        echo "TODOIST_API_KEY=$(ask_question 'Todoist API Token' '')" >> .env
        print_success "Todoist configured"
    else
        echo "TODOIST_API_KEY=" >> .env
    fi
    echo ""

    # Other settings
    DEFAULT_LOCATION=$(ask_question "Default location (for weather/traffic)" "Marysville, OH")
    echo "DEFAULT_LOCATION=$DEFAULT_LOCATION" >> .env
    echo "MAX_EMAILS_TO_FETCH=20" >> .env
    echo "MAX_NEWS_ARTICLES=10" >> .env
    echo "DEBUG=false" >> .env
    echo 'ALLOWED_ORIGINS=["*"]' >> .env

    print_success "Configuration saved to .env"
}

setup_systemd_service() {
    if ! ask_yes_no "Set up systemd service (auto-start on boot)?" "y"; then
        return
    fi

    print_info "Creating systemd service..."

    local service_file="/etc/systemd/system/$APP_NAME.service"

    sudo tee "$service_file" > /dev/null << EOF
[Unit]
Description=Daily Digest API
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$APP_DIR
Environment="PATH=$APP_DIR/venv/bin"
ExecStart=$APP_DIR/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    # Reload systemd
    sudo systemctl daemon-reload

    # Enable service
    sudo systemctl enable "$APP_NAME" > /dev/null 2>&1

    print_success "Systemd service created and enabled"
}

start_application() {
    if ask_yes_no "Start the application now?" "y"; then
        if systemctl is-active --quiet "$APP_NAME" 2>/dev/null; then
            print_info "Starting via systemd..."
            sudo systemctl start "$APP_NAME"
            sleep 2
            if systemctl is-active --quiet "$APP_NAME"; then
                print_success "Application started via systemd"
            else
                print_error "Failed to start via systemd"
                print_info "Check logs: sudo journalctl -u $APP_NAME -f"
            fi
        else
            print_info "Starting application manually..."
            cd "$APP_DIR"
            source venv/bin/activate
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > "$APP_DIR/app.log" 2>&1 &
            print_success "Application started in background"
        fi
    fi
}

print_completion() {
    print_header
    echo -e "${GREEN}Installation Complete!${NC}"
    echo ""
    echo "Your Daily Digest API is ready!"
    echo ""
    echo "📍 Installation directory: $APP_DIR"
    echo "🌐 API endpoint: http://localhost:8000"
    echo "📚 API docs: http://localhost:8000/docs"
    echo ""
    echo "Common commands:"
    echo "  cd $APP_DIR"
    echo "  source venv/bin/activate"
    echo "  uvicorn main:app --reload         # Run in development mode"
    echo "  python test_api.py                # Test the API"
    echo ""

    if systemctl is-enabled --quiet "$APP_NAME" 2>/dev/null; then
        echo "Systemd service commands:"
        echo "  sudo systemctl status $APP_NAME    # Check status"
        echo "  sudo systemctl start $APP_NAME     # Start service"
        echo "  sudo systemctl stop $APP_NAME      # Stop service"
        echo "  sudo systemctl restart $APP_NAME   # Restart service"
        echo "  sudo journalctl -u $APP_NAME -f    # View logs"
        echo ""
    fi

    echo "Next steps:"
    echo "  1. Add any missing API keys to: $APP_DIR/.env"
    echo "  2. For Google APIs: python $APP_DIR/setup/get_google_tokens.py"
    echo "  3. Test: curl http://localhost:8000/health"
    echo "  4. Set up reverse proxy (nginx) for production"
    echo "  5. Configure firewall to allow port 8000"
    echo ""
    echo "Documentation:"
    echo "  📖 README: $APP_DIR/README.md"
    echo "  🔐 API Setup: $APP_DIR/API_SETUP.md"
    echo "  🔑 Google Setup: $APP_DIR/GOOGLE_SETUP.md"
    echo ""
    echo -e "${GREEN}Happy digesting! 🎉${NC}"
}

# Main installation flow
main() {
    print_header
    echo "This script will install Daily Digest API on your system."
    echo ""

    if ! ask_yes_no "Continue with installation?" "y"; then
        print_info "Installation cancelled"
        exit 0
    fi

    echo ""

    # Run installation steps
    check_os
    install_dependencies
    setup_application
    setup_python_environment
    configure_api_keys
    setup_systemd_service
    start_application

    echo ""
    print_completion
}

# Run main function
main
