"""
Delivery Service for sending digest summaries via email using Gmail API
"""
import base64
import re
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional
from config import settings
import logging

logger = logging.getLogger(__name__)


class DeliveryService:
    """Service for sending digest emails via Gmail API"""

    def __init__(self):
        self.client_id = settings.GMAIL_CLIENT_ID
        self.client_secret = settings.GMAIL_CLIENT_SECRET
        self.refresh_token = settings.GMAIL_REFRESH_TOKEN
        self.recipient_email = settings.DIGEST_RECIPIENT_EMAIL
        self.sender_name = settings.DIGEST_SENDER_NAME

    @staticmethod
    def is_configured() -> bool:
        """Check if the service is properly configured for sending emails"""
        return bool(
            settings.GMAIL_CLIENT_ID
            and settings.GMAIL_CLIENT_SECRET
            and settings.GMAIL_REFRESH_TOKEN
            and settings.DIGEST_RECIPIENT_EMAIL
        )

    def _markdown_to_html(self, text: str) -> str:
        """Convert markdown-style text to simple HTML"""
        lines = text.split('\n')
        html_lines = []
        in_list = False

        for line in lines:
            stripped = line.strip()

            # Headers
            if stripped.startswith('### '):
                if in_list:
                    html_lines.append('</ul>')
                    in_list = False
                html_lines.append(f'<h3 style="color:#333;margin:16px 0 8px 0;">{stripped[4:]}</h3>')
                continue
            if stripped.startswith('## '):
                if in_list:
                    html_lines.append('</ul>')
                    in_list = False
                html_lines.append(f'<h2 style="color:#222;margin:20px 0 10px 0;">{stripped[3:]}</h2>')
                continue
            if stripped.startswith('# '):
                if in_list:
                    html_lines.append('</ul>')
                    in_list = False
                html_lines.append(f'<h1 style="color:#111;margin:24px 0 12px 0;">{stripped[2:]}</h1>')
                continue

            # Bullet points
            if stripped.startswith('- ') or stripped.startswith('* '):
                if not in_list:
                    html_lines.append('<ul style="margin:8px 0;padding-left:20px;">')
                    in_list = True
                content = stripped[2:]
                content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', content)
                html_lines.append(f'<li style="margin:4px 0;">{content}</li>')
                continue

            # Close list if we're not in a bullet anymore
            if in_list and stripped:
                html_lines.append('</ul>')
                in_list = False

            # Empty lines
            if not stripped:
                if in_list:
                    html_lines.append('</ul>')
                    in_list = False
                html_lines.append('<br>')
                continue

            # Bold text
            content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', stripped)
            html_lines.append(f'<p style="margin:6px 0;color:#444;">{content}</p>')

        if in_list:
            html_lines.append('</ul>')

        return '\n'.join(html_lines)

    def _build_html_email(self, summary: str, date_str: str) -> str:
        """Build a clean HTML email body from the digest summary"""
        summary_html = self._markdown_to_html(summary)

        return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto;padding:20px;background-color:#f9f9f9;">
  <div style="background-color:#ffffff;border-radius:8px;padding:30px;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <div style="border-bottom:2px solid #4A90D9;padding-bottom:15px;margin-bottom:20px;">
      <h1 style="margin:0;color:#4A90D9;font-size:24px;">Daily Digest</h1>
      <p style="margin:5px 0 0 0;color:#888;font-size:14px;">{date_str}</p>
    </div>
    <div style="line-height:1.6;color:#333;">
      {summary_html}
    </div>
    <div style="border-top:1px solid #eee;margin-top:25px;padding-top:15px;text-align:center;color:#aaa;font-size:12px;">
      Generated by Daily Digest API
    </div>
  </div>
</body>
</html>"""

    async def send_digest_email(
        self,
        summary: str,
        recipient_email: Optional[str] = None,
    ) -> bool:
        """
        Send the digest summary via email using Gmail API.

        Args:
            summary: The digest summary text (markdown-style)
            recipient_email: Override recipient (defaults to DIGEST_RECIPIENT_EMAIL)

        Returns:
            True if email was sent successfully, False otherwise
        """
        to_email = recipient_email or self.recipient_email
        if not to_email:
            logger.error("No recipient email configured")
            return False

        if not (self.client_id and self.client_secret and self.refresh_token):
            logger.error("Gmail OAuth credentials not configured for sending")
            return False

        try:
            from google.oauth2.credentials import Credentials
            from google.auth.transport.requests import Request
            from googleapiclient.discovery import build

            creds = Credentials(
                token=None,
                refresh_token=self.refresh_token,
                client_id=self.client_id,
                client_secret=self.client_secret,
                token_uri='https://oauth2.googleapis.com/token'
            )
            if creds.expired or not creds.valid:
                creds.refresh(Request())

            service = build('gmail', 'v1', credentials=creds)

            # Build the email
            date_str = datetime.now().strftime('%B %d, %Y')
            subject = f"Your Daily Digest - {date_str}"

            message = MIMEMultipart('alternative')
            message['To'] = to_email
            message['Subject'] = subject
            if self.sender_name:
                # Get the authenticated user's email for the From field
                profile = service.users().getProfile(userId='me').execute()
                sender_email = profile.get('emailAddress', '')
                message['From'] = f"{self.sender_name} <{sender_email}>"

            # Plain text fallback
            message.attach(MIMEText(summary, 'plain'))

            # HTML version
            html_body = self._build_html_email(summary, date_str)
            message.attach(MIMEText(html_body, 'html'))

            # Encode and send
            raw = base64.urlsafe_b64encode(message.as_bytes()).decode('utf-8')
            service.users().messages().send(
                userId='me',
                body={'raw': raw}
            ).execute()

            logger.info(f"Digest email sent to {to_email}")
            return True

        except Exception as e:
            logger.error(f"Failed to send digest email: {str(e)}")
            return False
